#!/usr/bin/env bash
set -euo pipefail


AZTEC_VERSION=""
# go from the current dir to the root of the filesystem and find the first .aztecrc or .gaztecrc file
dir=$(pwd)
while [[ $dir != "/" ]]; do
  # fail if both .aztecrc and .gaztecrc files are found
  if [[ -f "$dir/.aztecrc" && -f "$dir/.gaztecrc" ]]; then
    echo "Found both .aztecrc and .gaztecrc files in $dir. Please only use one of them." >&2
    exit 1
  fi

  if [[ -f "$dir/.aztecrc" ]]; then
    AZTEC_VERSION=$(cat $dir/.aztecrc | tr -d '\n')
    echo "Using aztec version $AZTEC_VERSION from $dir/.aztecrc" >&2
    break
  fi

  if [[ -f "$dir/.gaztecrc" ]]; then
    AZTEC_VERSION=$(cat $dir/.gaztecrc | tr -d '\n')
    echo "Using aztec version $AZTEC_VERSION from $dir/.gaztecrc" >&2
    # deprecation warning
    echo "WARNING: .gaztecrc is deprecated. Please rename to .aztecrc instead." >&2
    break
  fi

  dir=$(dirname $dir)
done

# fallback
if [[ -z "$AZTEC_VERSION" ]]; then
  echo "No .aztecrc file found in the current or parent directories starting from $(pwd). Falling back to the latest version." >&2
  # fetch the latest version from github releases, remove the v prefix
  AZTEC_VERSION=$(curl -s https://api.github.com/repos/AztecProtocol/aztec-packages/releases/latest | jq -r '.tag_name' | sed 's/^v//')
  echo "Latest version is $AZTEC_VERSION" >&2
fi

AZTEC_PATH="$HOME/.aztec"
AZTEC_UP="$AZTEC_PATH/bin/aztec-up"

if [[ ! -f "$AZTEC_UP" ]]; then
  echo "aztec-up could not be found. Installing it..." >&2
  # FOUNDRY_DIR is needed due to a bug in aztec-up
  FOUNDRY_DIR="$HOME/.foundry" VERSION=$AZTEC_VERSION NON_INTERACTIVE=1 bash -i <(curl -sL https://install.aztec.network/$AZTEC_VERSION)
fi

if ! $AZTEC_UP list | grep $AZTEC_VERSION; then
  echo "Installing aztec version $AZTEC_VERSION..." >&2
  $AZTEC_UP install $AZTEC_VERSION
fi

$AZTEC_UP use $AZTEC_VERSION

# needed due to a bug. Without this line, it tries to use bb from ~/.bb
export BB="$AZTEC_PATH/versions/$AZTEC_VERSION/node_modules/.bin/bb"
# needed due to a bug. Without this line, it tries to use nargo from ~/.nargo
export NARGO="$AZTEC_PATH/versions/$AZTEC_VERSION/bin/nargo"

# bug on CI with nvm
if [[ -n "${CI:-}" ]] && command -v npm >/dev/null 2>&1; then
  npm config delete prefix
fi

# on github CI (GITHUB_PATH exists), add the aztec path to the path
if [[ -n "${GITHUB_PATH:-}" ]]; then
  echo "$AZTEC_PATH/versions/$AZTEC_VERSION/bin" >> $GITHUB_PATH
  echo "$AZTEC_PATH/versions/$AZTEC_VERSION/node_modules/.bin" >> $GITHUB_PATH
fi

AZTEC="$AZTEC_PATH/versions/$AZTEC_VERSION/node_modules/.bin/aztec"
